#!/usr/bin/env bash
# ============================================================================================ #
#: Title           : boxed_passwd                                                              #
#: Sypnosis        : boxex_passwd [SHELL]                                                      #
#: Date Created    : Sat 27 Jun 2020 14:12:16 PM PST  /  Sat Jun 27 06:12:16 UTC 2020          #
#: Last Edit       : Sat 27 Jun 2020 17:01:06 PM PST  /  Sat Jun 27 09:01:06 UTC 2020          #
#: License         : GPL3+                                                                     #
#: Version         : 1.0.3                                                                     #
#: Author          : Jason V. Ferrer '<jason@ferrer.com.ph>'                                   #
#: Description     : Print a nice boxed ouput of selected field from /etc/passwd file.         #
#: Options         : NONE                                                                      #
#: Home Page       : NONE                                                                      #
#: ExtComm         : ed,column,grep,wc                                                         #
#: Copyright       : Jason V. Ferrer 2020-2021                                                 #
# ============================================================================================ #

# ******************************************************************************************** #
#                             The scriptname without the pathname.                             #
# ******************************************************************************************** #

script_name=${BASH_SOURCE##*/}

# ******************************************************************************************** #
#   Warn and die functions, for exit messages and default status or an optional exit status.   #
# ******************************************************************************************** #

warn() {
  printf '%s: %s %s\n' "$script_name" "$@"
}

die() {
  local st=$?
  case $3 in
    *[^0-9]*|'') :;;
    *) st=$3;;
  esac

  case $st in
    0) warn "$1" "$2" ;;
    *) warn "$1" "$2" >&2 ;;
  esac

  exit "$st"
}

# ******************************************************************************************** #
#          Check for the required app/executable is with in your PATH, exit otherwise.         #
# ******************************************************************************************** #

ExtComm=( ed column grep wc )
MissingMessage="is either not installed or it is not in your PATH!"
ExitMessage="Please install the following: "

if (( ${#ExtComm[@]} )); then
  for apps in "${ExtComm[@]}"; do
    if ! type -P "$apps" >/dev/null; then
      printf '%s %s\n' "$apps" "$MissingMessage" >&2
      Missing+=("$apps")
    fi
  done
fi

(( ${#Missing[@]} )) && die "$ExitMessage[${Missing[*]}]" "or add it in your PATH. exiting now!" 127

# ******************************************************************************************** #
#            Assign the first argument (which is the shell) to the variable shell.             #
# ******************************************************************************************** #

shell=$1

# ******************************************************************************************** #
#                        Harcoded file assignment for /etc/passwd file.                        #
# ******************************************************************************************** #

file=/etc/passwd

# ******************************************************************************************** #
#             Check if there is an argument given, default to all shell otherwise.             #
# ******************************************************************************************** #

if [[ $shell ]]; then
  line_count=$(grep -c "/${shell:-.*}$" "$file")
else
  line_count=$(wc -l < "$file")
fi

# ******************************************************************************************** #
#                If there no matching shell given, exit the script immediately.                #
# ******************************************************************************************** #

((line_count)) || {
  die 'There are no match for' "$shell"
}

# ******************************************************************************************** #
#             Multiply the lines by two for the dashes and + for the other lines.              #
# ******************************************************************************************** #

total=$((line_count * 2))

# ******************************************************************************************** #
#               Add the ed code to add the lines needed for the dashes and plus.               #
# ******************************************************************************************** #

for ((i=1;i<=total;i+=2)); do
  array+=(
    "$i"t"$i"
    "$((i+1))s/|/+/g"
    "$((i+1))s/[^+]/-/g"
  )
done

# ******************************************************************************************** #
#                  Add more ed code to add the header line and the last line.                  #
# ******************************************************************************************** #

array=(
  '$t$'
  '$s/|/+/g'
  '$s/[^+]/-/g'
  "${array[@]}"
  '1t0'
  '1s/|/+/g'
  '1s/[^+]/-/g'
  ,p
  Q
)

# ******************************************************************************************** #
#                 Add the header message at the first line of the /etc/passwd.                 #
# ******************************************************************************************** #

mapfile -t passwd < <(
  printf '0a\nUsername:2:UID:GID:5:Home:Shell:%s\n.\n,p\nQ\n' "$shell" |
  ed -s "$file"
)

# ******************************************************************************************** #
#       Parse the /etc/passwd file and extract the correct value and format accordingly.       #
# ******************************************************************************************** #

ed -s <(
  while IFS=: read -r user_name _ uid gid _ home user_shell last; do
    [[ $user_shell != *$shell && $last != *$shell ]] && continue
    printf '| %s | %s | %s | %s | %s |\n' "$user_name" "$uid" "$gid" "$home" "$user_shell"
  done < <(printf '%s\n' "${passwd[@]}")  | column -t
)< <(printf '%s\n' H "${array[@]}")

# ============================================================================================ #
#                                    >>> END OF SCRIPT <<<                                     #
# ============================================================================================ #
